[project]
name = "pydeploy"
version = "0.1"

[project.optional-dependencies]
dev = ["black"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
pydeploy = "pydeploy.deploy:main"
