[project]
name = "pygame_example"
version = "0.1"
dependencies = ["pygame"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.gui-scripts]
mygame = "pygame_example:main"
